<a href="https://colab.research.google.com/github/veluguladurgaprasad99/numpy/blob/main/numpyinbuilt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Array (`ndarray`) – Information Methods

These attributes provide information about the structure, dimensions, data type, and memory usage of a NumPy array.

| Method / Attribute | Definition                                                                 | Example      | Output                  |
| ------------------ | -------------------------------------------------------------------------- | ------------ | ----------------------- |
| `shape`            | Returns the shape (rows, columns, etc.) of the array.                      | `a.shape`    | `(2, 3)`                |
| `ndim`             | Returns the number of dimensions.                                          | `a.ndim`     | `2`                     |
| `size`             | Returns the total number of elements.                                      | `a.size`     | `6`                     |
| `dtype`            | Returns the data type of elements.                                         | `a.dtype`    | `int64`                 |
| `itemsize`         | Returns the size (in bytes) of one element.                                | `a.itemsize` | `8`                     |
| `nbytes`           | Returns the total memory used by the array.                                | `a.nbytes`   | `48`                    |
| `T`                | Returns the transpose of the array.                                        | `a.T`        | Transposed array        |
| `strides`          | Returns the number of bytes to move to the next element in each dimension. | `a.strides`  | `(24, 8)`               |
| `flags`            | Displays memory layout information.                                        | `a.flags`    | Array flags information |
| `data`             | Returns the memory buffer information.                                     | `a.data`     | Memory view object      |

## Example

```python
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Data Type:", a.dtype)
print("Item Size:", a.itemsize)
print("Memory Used:", a.nbytes)
```

### Output

```text
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64
Item Size: 8
Memory Used: 48
```

## Interview Definition

Information Methods are attributes used to inspect the structure, dimensions, data type, and memory usage of a NumPy array.

### Most Frequently Used

* `shape`
* `ndim`
* `size`
* `dtype`
* `nbytes`


In [ ]:
pip install numpy

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Shape:", a.shape)#returns the shape(rows,cols)
print("Dimensions:", a.ndim)#Returns the number of dimensions.
print("Size:", a.size)#Returns the total number of elements.
print("Data Type:", a.dtype)#Returns the data type of elements.
print("Item Size:", a.itemsize)#Returns the size (in bytes) of one element.
print("Memory Used:", a.nbytes)#Returns total memory used by the array.
print("Transpose array",a.T)#gives transpose
print(a.strides)
print(a.flags)
print(a.data)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64
Item Size: 8
Memory Used: 48
Transpose array [[1 4]
 [2 5]
 [3 6]]
(24, 8)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



# 2. NumPy Array (`ndarray`) – Reshaping Methods

These methods are used to change the shape or structure of an array without changing its data.

| Method        | Definition                                                                      | Example           |
| ------------- | ------------------------------------------------------------------------------- | ----------------- |
| `reshape()`   | Changes the shape of the array.                                                 | `a.reshape(2,3)`  |
| `flatten()`   | Converts a multidimensional array into a 1D array (returns a copy).             | `a.flatten()`     |
| `ravel()`     | Converts a multidimensional array into a 1D array (returns a view if possible). | `a.ravel()`       |
| `transpose()` | Swaps rows and columns.                                                         | `a.transpose()`   |
| `T`           | Shortcut for transpose.                                                         | `a.T`             |
| `squeeze()`   | Removes dimensions of size 1.                                                   | `a.squeeze()`     |
| `swapaxes()`  | Interchanges two axes.                                                          | `a.swapaxes(0,1)` |
| `resize()`    | Changes the array shape permanently.                                            | `a.resize((3,2))` |

## `reshape()`

**Definition:** Changes the shape of an array without changing its data.

```python id="a4y1fw"
import numpy as np

a = np.array([1,2,3,4,5,6])

print(a.reshape(2,3))
```

**Output**

```text id="g0h6e9"
[[1 2 3]
 [4 5 6]]
```

---

## `flatten()`

**Definition:** Converts a multidimensional array into a 1D array and returns a copy.

```python id="0k6ypz"
a = np.array([[1,2],
              [3,4]])

print(a.flatten())
```

**Output**

```text id="9r0r7x"
[1 2 3 4]
```

---

## `ravel()`

**Definition:** Converts a multidimensional array into a 1D array and returns a view whenever possible.

```python id="jhmfzw"
a = np.array([[1,2],
              [3,4]])

print(a.ravel())
```

**Output**

```text id="nl7rqz"
[1 2 3 4]
```

---

## `transpose()`

**Definition:** Converts rows into columns and columns into rows.

```python id="k26vse"
a = np.array([[1,2,3],
              [4,5,6]])

print(a.transpose())
```

**Output**

```text id="wghyqz"
[[1 4]
 [2 5]
 [3 6]]
```

---

## `T`

**Definition:** Shortcut for transpose.

```python id="zodxmw"
a = np.array([[1,2,3],
              [4,5,6]])

print(a.T)
```

**Output**

```text id="6alyl9"
[[1 4]
 [2 5]
 [3 6]]
```

---

## `squeeze()`

**Definition:** Removes dimensions whose size is 1.

```python id="8b4zji"
a = np.array([[[1,2,3]]])

print(a.shape)

b = a.squeeze()

print(b.shape)
```

**Output**

```text id="swxq7m"
(1, 1, 3)
(3,)
```

---

## `swapaxes()`

**Definition:** Swaps two specified axes.

```python id="i9olsl"
a = np.array([[1,2,3],
              [4,5,6]])

print(a.swapaxes(0,1))
```

**Output**

```text id="0xgdz9"
[[1 4]
 [2 5]
 [3 6]]
```

---

## `resize()`

**Definition:** Changes the shape of the array permanently.

```python id="9jzygc"
a = np.array([1,2,3,4,5,6])

a.resize((3,2))

print(a)
```

**Output**

```text id="dq72mk"
[[1 2]
 [3 4]
 [5 6]]
```

## Interview Notes

### Difference Between `flatten()` and `ravel()`

| Method      | Returns                     |
| ----------- | --------------------------- |
| `flatten()` | Copy of array               |
| `ravel()`   | View of array (if possible) |

### Most Frequently Used Reshaping Methods

* `reshape()`
* `flatten()`
* `ravel()`
* `transpose()`
* `T`

These methods are commonly used in Data Science, Machine Learning, and Deep Learning for data preprocessing and feature engineering.


In [ ]:
#reshape():Changes the shape of an array without changing its data.

import numpy as np

a = np.array([1,2,3,4,5,6])

print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
#flatten():Converts a multidimensional array into a 1D array and returns a copy.
a = np.array([[1,2],[3,4]])

print(a.flatten())

[1 2 3 4]


In [ ]:
#ravel():Converts an array into 1D and returns a view whenever possible.
a = np.array([[1,2],[3,4]])

print(a.ravel())

[1 2 3 4]


In [ ]:
#transpose():Converts rows into columns and columns into rows.
a = np.array([[1,2,3],
              [4,5,6]])

print(a.transpose())


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#squeeze():Removes dimensions whose size is 1.
a = np.array([[[1,2,3]]])

print(a.shape)

b = a.squeeze()
print(b)
print(b.shape)

(1, 1, 3)
[1 2 3]
(3,)


In [ ]:
#swapaxes(): Swaps two specified axes
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(a.swapaxes(1,0))
print(a.swapaxes(0,1))
a = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

print("Shape:", a.shape)
print(a)
b = a.swapaxes(0,1)

print("Shape:", b.shape)
print(b)
c = a.swapaxes(1,2)

print("Shape:", c.shape)
print(c)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape: (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
Shape: (2, 3, 2)
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [ ]:
#resize():Changes the shape of the array permanently
a = np.array([1,2,3,4,5,6])

a.resize((3,2))

print(a)

[[1 2]
 [3 4]
 [5 6]]


# 3. NumPy Array (`ndarray`) – Statistical Methods

These methods are used to perform statistical and mathematical calculations on array elements.

| Method | Definition | Example |
|----------|------------|---------|
| `sum()` | Returns the sum of all elements. | `a.sum()` |
| `mean()` | Returns the average value. | `a.mean()` |
| `min()` | Returns the smallest value. | `a.min()` |
| `max()` | Returns the largest value. | `a.max()` |
| `std()` | Returns the standard deviation. | `a.std()` |
| `var()` | Returns the variance. | `a.var()` |
| `prod()` | Returns the product of all elements. | `a.prod()` |
| `cumsum()` | Returns cumulative sum. | `a.cumsum()` |
| `cumprod()` | Returns cumulative product. | `a.cumprod()` |
| `median()` | Returns the median value. | `np.median(a)` |
| `percentile()` | Returns the percentile value. | `np.percentile(a,50)` |



In [ ]:
#sum():Returns the sum of all array elements.
#percentile():Returns the value below which a given percentage of observations fall.
import numpy as np
a = np.array([1,2,3,4])
print(a.sum())
a = np.array([[1,2,3],
              [4,5,6]])
print("0Column-wise sum.:",a.sum(axis=0))
print("1Row-wise sum.:",a.sum(axis=1))
a = np.array([10,20,30,40,50])
print(np.percentile(a,50))

10
0Column-wise sum.: [5 7 9]
1Row-wise sum.: [ 6 15]
30.0


In [ ]:
#mean():Returns the average value.
#median(): Returns the middle value after sorting.
a = np.array([1,2,3,4])
print(a.mean())
a = np.array([1,2,3,4,5])
print(np.median(a))

2.5
3.0


In [ ]:
# min(): Returns the minimum value.
# max(): Returns the maximum value.
a = np.array([1,2,3,4])

print(a.max())
print(a.min())

4
1


In [ ]:
# var(): Returns the variance.
# std(): Returns the standard deviation.
# prod(): Returns the product of all elements.
# cumsum(): Returns cumulative sum.
# cumprod(): Returns cumulative product.
a = np.array([1,2,3,4])

print(a.std())
print(a.var())
print(a.prod())
print(a.cumsum())
print(a.cumprod())

1.118033988749895
1.25
24
[ 1  3  6 10]
[ 1  2  6 24]


# 4. NumPy Array (`ndarray`) – Sorting & Searching Methods

These methods are used to sort data, find positions of elements, and search for specific values in an array.

| Method | Definition | Example |
|----------|------------|---------|
| `sort()` | Sorts the array. | `a.sort()` |
| `argsort()` | Returns indices that would sort the array. | `a.argsort()` |
| `argmax()` | Returns index of the maximum value. | `a.argmax()` |
| `argmin()` | Returns index of the minimum value. | `a.argmin()` |
| `searchsorted()` | Finds insertion index for a value. | `a.searchsorted(25)` |
| `nonzero()` | Returns indices of non-zero elements. | `a.nonzero()` |
| `where()` | Returns indices matching a condition. | `np.where(a > 5)` |
| `unique()` | Returns unique elements. | `np.unique(a)` |

## `sort()`

**Definition:** Sorts the array in ascending order.

```python
import numpy as np

a = np.array([30, 10, 20])

print(np.sort(a))
```

**Output**

```text
[10 20 30]
```

---

## `argsort()`

**Definition:** Returns the indices that would sort the array.

```python
a = np.array([30, 10, 20])

print(a.argsort())
```

**Output**

```text
[1 2 0]
```

Explanation:

```text
Index 1 → 10
Index 2 → 20
Index 0 → 30
```

---

## `argmax()`

**Definition:** Returns the index of the largest value.

```python
a = np.array([30, 10, 20])

print(a.argmax())
```

**Output**

```text
0
```

---

## `argmin()`

**Definition:** Returns the index of the smallest value.

```python
a = np.array([30, 10, 20])

print(a.argmin())
```

**Output**

```text
1
```

---

## `searchsorted()`

**Definition:** Returns the position where a value should be inserted to maintain sorted order.

```python
a = np.array([10, 20, 30, 40])

print(a.searchsorted(25))
```

**Output**

```text
2
```

Explanation:

```text
[10, 20, 25, 30, 40]
         ↑
      Index 2
```

---

## `nonzero()`

**Definition:** Returns indices of non-zero elements.

```python
a = np.array([0, 10, 0, 20, 30])

print(a.nonzero())
```

**Output**

```text
(array([1, 3, 4]),)
```

---

## `where()`

**Definition:** Returns indices where a condition is True.

```python
a = np.array([10, 20, 30, 40, 50])

print(np.where(a > 25))
```

**Output**

```text
(array([2, 3, 4]),)
```

---

## `unique()`

**Definition:** Returns unique values from the array.

```python
a = np.array([1, 2, 2, 3, 3, 3, 4])

print(np.unique(a))
```

**Output**

```text
[1 2 3 4]
```

---

## 2D Array Example

```python
a = np.array([[5,2,8],
              [1,9,3]])

print(np.sort(a))
```

**Output**

```text
[[2 5 8]
 [1 3 9]]
```

---

## Most Frequently Used Sorting & Searching Methods

- `sort()`
- `argsort()`
- `argmax()`
- `argmin()`
- `where()`
- `unique()`

These methods are heavily used in Data Analysis, Feature Engineering, Machine Learning, and Data Cleaning.

In [ ]:
# sort(): Sorts array elements in ascending order.
# argsort(): Returns indices that would sort the array.
a = np.array([30,10,20])

a.sort()

print(a)
a = np.array([30,10,20])

print(a.argsort())



[10 20 30]
[1 2 0]


In [ ]:
# argmin(): Returns the index of the minimum value.
# argmax(): Returns the index of the maximum value.
a = np.array([10,50,30])

print(a.argmax())
a = np.array([10,50,30])

print(a.argmin())


1
0


In [ ]:
# searchsorted(): Returns the index where a value should be inserted to maintain
# nonzero(): Returns indices of non-zero elements.
# where(): Returns indices where a condition is true.
# unique(): Returns unique values from the array.
# count_nonzero(): Counts non-zero elements.
# argwhere(): Returns indices where a condition is true.



a = np.array([10,20,30,40])

print(a.searchsorted(25))
a = np.array([1,0,2,0,3])

print(a.nonzero())
a = np.array([10,20,30,40])

print(np.where(a > 20))
a = np.array([1,2,2,3,3,4])

print(np.unique(a))
a = np.array([1,0,2,0,3])

print(np.count_nonzero(a))
a = np.array([[1,5],
              [8,2]])

print(np.argwhere(a > 4))

2
(array([0, 2, 4]),)
(array([2, 3]),)
[1 2 3 4]
3
[[0 1]
 [1 0]]


# 5. NumPy Array (`ndarray`) – Mathematical & Arithmetic Methods

These methods perform mathematical operations on array elements.

| Method | Definition | Example |
|----------|------------|---------|
| `sum()` | Sum of elements | `a.sum()` |
| `add()` | Adds elements | `np.add(a,b)` |
| `subtract()` | Subtracts elements | `np.subtract(a,b)` |
| `multiply()` | Multiplies elements | `np.multiply(a,b)` |
| `divide()` | Divides elements | `np.divide(a,b)` |
| `power()` | Raises elements to a power | `np.power(a,2)` |
| `sqrt()` | Square root | `np.sqrt(a)` |
| `abs()` | Absolute value | `np.abs(a)` |
| `round()` | Rounds values | `np.round(a)` |
| `clip()` | Limits values to a range | `np.clip(a,1,5)` |
| `mod()` | Remainder after division | `np.mod(a,2)` |
| `floor()` | Round down | `np.floor(a)` |
| `ceil()` | Round up | `np.ceil(a)` |



In [ ]:
# add(): Adds corresponding elements.
# subtract(): Subtracts corresponding elements.
# multiply(): Multiplies corresponding elements.
# divide(): Divides corresponding elements.
# power(): Raises each element to a given power.
# sqrt(): Computes square root.
# abs(): Returns absolute values.
# round(): Rounds values to nearest integer.
# clip(): Restricts values within a range.
# mod(): Returns remainder after division.
# floor(): Rounds down to nearest integer.
# ceil(): Rounds up to nearest integer.

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.add(a,b))


a = np.array([10,20,30])
b = np.array([1,2,3])

print(np.subtract(a,b))

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.multiply(a,b))
a = np.array([10,20,30])
b = np.array([2,4,5])
print(np.divide(a,b))
a = np.array([1,2,3])

print(np.power(a,2))
a = np.array([1,4,9,16])

print(np.sqrt(a))
a = np.array([-1,-2,3])

print(np.abs(a))
a = np.array([1.45,2.67,3.22])

print(np.round(a))
a = np.array([1,5,10])

print(np.clip(a,2,8))
a = np.array([10,11,12])

print(np.mod(a,2))
a = np.array([1.9,2.7,3.2])

print(np.floor(a))
a = np.array([1.2,2.1,3.8])

print(np.ceil(a))

[5 7 9]
[ 9 18 27]
[ 4 10 18]
[5. 5. 6.]
[1 4 9]
[1. 2. 3. 4.]
[1 2 3]
[1. 3. 3.]
[2 5 8]
[0 1 0]
[1. 2. 3.]
[2. 3. 4.]


In [ ]:
# NumPy Array (ndarray) – Data Type & Conversion Methods

# astype(): Converts elements from one data type to another.
# copy(): Creates a completely separate copy of the array.
# view(): Creates a view that shares the same data.
# tolist(): Converts NumPy array to Python list.
# item(): Extracts a Python scalar value.
# tobytes(): Converts array into bytes.
# byteswap(): Swaps byte order of array elements.
# dtype: Returns the data type of the array.
# itemsize: Returns memory occupied by one element.

import numpy as np

# astype()
a = np.array([1,2,3])
print(a.astype(float))

# copy()
a = np.array([1,2,3])

b = a.copy()
b[0] = 100

print(a)
print(b)

# view()
a = np.array([1,2,3])

b = a.view()
b[0] = 100

print(a)
print(b)

# tolist()
a = np.array([1,2,3])

print(a.tolist())

# item()
a = np.array([100])

print(a.item())

# tobytes()
a = np.array([1,2,3])

print(a.tobytes())

# byteswap()
a = np.array([1,2,3])

print(a.byteswap())

# dtype
a = np.array([1,2,3])

print(a.dtype)

# itemsize
a = np.array([1,2,3])

print(a.itemsize)



# ##copy()  -> New memory created
# view()  -> Same memory shared

[1. 2. 3.]
[1 2 3]
[100   2   3]
[100   2   3]
[100   2   3]
[1, 2, 3]
100
b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00'
[ 72057594037927936 144115188075855872 216172782113783808]
int64
8


In [ ]:
# NumPy Array (ndarray) – Array Manipulation Methods

# append(): Adds elements at the end of an array.
# insert(): Inserts elements at a specified position.
# delete(): Removes elements from an array.
# concatenate(): Joins two or more arrays.
# stack(): Stacks arrays along a new axis.
# hstack(): Stacks arrays horizontally.
# vstack(): Stacks arrays vertically.
# split(): Splits an array into multiple sub-arrays.
# hsplit(): Splits an array horizontally.
# vsplit(): Splits an array vertically.
# repeat(): Repeats array elements.
# tile(): Repeats the entire array multiple times.

import numpy as np

# append()
a = np.array([1,2,3])
print(np.append(a, 4))

# insert()
a = np.array([1,2,3])
print(np.insert(a, 1, 10))

# delete()
a = np.array([1,2,3,4])
print(np.delete(a, 2))

# concatenate()
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

# stack()
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.stack((a,b)))

# hstack()
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.hstack((a,b)))

# vstack()
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

# split()
a = np.array([1,2,3,4,5,6])
print(np.split(a, 3))

# hsplit()
a = np.array([[1,2,3,4],
              [5,6,7,8]])
print(np.hsplit(a, 2))

# vsplit()
a = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])
print(np.vsplit(a, 2))

# repeat()
a = np.array([1,2,3])
print(np.repeat(a, 2))

# tile()
a = np.array([1,2,3])
print(np.tile(a, 3))

[1 2 3 4]
[ 1 10  2  3]
[1 2 4]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[1 1 2 2 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
# NumPy Array (ndarray) – Indexing, Slicing & Selection Methods

# take(): Selects elements by index.
# put(): Replaces elements at specified indices.
# compress(): Selects elements using a boolean condition.
# extract(): Extracts elements satisfying a condition.
# where(): Returns indices where a condition is True.
# nonzero(): Returns indices of non-zero elements.
# argwhere(): Returns indices where a condition is True.
# choose(): Selects values from multiple arrays based on index array.

import numpy as np

# take()
a = np.array([10,20,30,40,50])
print(np.take(a, [0,2,4]))

# put()
a = np.array([10,20,30,40,50])
np.put(a, [1,3], [100,200])
print(a)

# compress()
a = np.array([10,20,30,40,50])
condition = [True, False, True, False, True]
print(np.compress(condition, a))

# extract()
a = np.array([10,20,30,40,50])
print(np.extract(a > 25, a))

# where()
a = np.array([10,20,30,40,50])
print(np.where(a > 25))

# nonzero()
a = np.array([1,0,2,0,3])
print(np.nonzero(a))

# argwhere()
a = np.array([[10,20],
              [30,40]])
print(np.argwhere(a > 20))

# choose()
choice = np.array([0,1,0,1])

a = np.array([10,20,30,40])
b = np.array([100,200,300,400])

print(np.choose(choice, [a,b]))

[10 30 50]
[ 10 100  30 200  50]
[10 30 50]
[30 40 50]
(array([2, 3, 4]),)
(array([0, 2, 4]),)
[[1 0]
 [1 1]]
[ 10 200  30 400]


In [ ]:
# NumPy Array (ndarray) – Random Module Methods

# np.random.rand(): Generates random numbers between 0 and 1.
# np.random.randn(): Generates random numbers from a normal distribution.
# np.random.randint(): Generates random integers within a range.
# np.random.choice(): Randomly selects elements from an array.
# np.random.shuffle(): Randomly shuffles an array in-place.
# np.random.permutation(): Returns a shuffled copy of an array.
# np.random.seed(): Sets seed for reproducible random numbers.

import numpy as np

# rand()
print(np.random.rand(3))

# randn()
print(np.random.randn(3))

# randint()
print(np.random.randint(1, 10, size=5))

# choice()
a = np.array([10,20,30,40,50])
print(np.random.choice(a, size=3))

# shuffle()
a = np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

# permutation()
a = np.array([1,2,3,4,5])
print(np.random.permutation(a))

# seed()
np.random.seed(42)
print(np.random.randint(1, 100, 5))

np.random.seed(42)
print(np.random.randint(1, 100, 5))

[0.37089791 0.24428853 0.7394324 ]
[1.86044507 0.9022882  0.55872444]
[5 3 4 1 5]
[10 40 50]
[1 3 2 4 5]
[5 4 2 3 1]
[52 93 15 72 61]
[52 93 15 72 61]


In [ ]:
# NumPy Array (ndarray) – Array Creation Methods

# np.array(): Creates an array from a list or tuple.
# np.zeros(): Creates an array filled with zeros.
# np.ones(): Creates an array filled with ones.
# np.empty(): Creates an uninitialized array.
# np.full(): Creates an array filled with a specified value.
# np.arange(): Creates an array with evenly spaced values.
# np.linspace(): Creates an array with evenly spaced values between two limits.
# np.logspace(): Creates an array with logarithmically spaced values.
# np.eye(): Creates an identity matrix.
# np.identity(): Creates an identity matrix.
# np.diag(): Creates or extracts diagonal elements.

import numpy as np

# array()
print(np.array([1,2,3,4]))

# zeros()
print(np.zeros((2,3)))

# ones()
print(np.ones((2,3)))

# empty()
print(np.empty((2,3)))

# full()
print(np.full((2,3), 5))

# arange()
print(np.arange(1,11,2))

# linspace()
print(np.linspace(0,10,5))

# logspace()
print(np.logspace(1,3,3))

# eye()
print(np.eye(3))

# identity()
print(np.identity(3))

# diag() - Create diagonal matrix
print(np.diag([1,2,3]))

# diag() - Extract diagonal
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.diag(a))

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]
[  10.  100. 1000.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 5 9]


In [ ]:
# NumPy Array (ndarray) – String Operations

# np.char.upper(): Converts strings to uppercase.
# np.char.lower(): Converts strings to lowercase.
# np.char.capitalize(): Capitalizes first letter.
# np.char.title(): Converts first letter of each word to uppercase.
# np.char.split(): Splits strings.
# np.char.join(): Joins strings.
# np.char.replace(): Replaces substrings.
# np.char.strip(): Removes leading/trailing spaces.
# np.char.find(): Finds substring position.
# np.char.count(): Counts occurrences of substring.

import numpy as np

# upper()
a = np.array(['python', 'numpy'])
print(np.char.upper(a))

# lower()
a = np.array(['PYTHON', 'NUMPY'])
print(np.char.lower(a))

# capitalize()
a = np.array(['python', 'numpy'])
print(np.char.capitalize(a))

# title()
a = np.array(['data science', 'machine learning'])
print(np.char.title(a))

# split()
a = np.array(['data science', 'machine learning'])
print(np.char.split(a))

# join()
print(np.char.join('-', ['ABC', 'XYZ']))

# replace()
a = np.array(['hello world'])
print(np.char.replace(a, 'world', 'numpy'))

# strip()
a = np.array(['  python  '])
print(np.char.strip(a))

# find()
a = np.array(['machine learning'])
print(np.char.find(a, 'learn'))

# count()
a = np.array(['banana'])
print(np.char.count(a, 'a'))

['PYTHON' 'NUMPY']
['python' 'numpy']
['Python' 'Numpy']
['Data Science' 'Machine Learning']
[list(['data', 'science']) list(['machine', 'learning'])]
['A-B-C' 'X-Y-Z']
['hello numpy']
['python']
[8]
[3]


In [ ]:
# NumPy Array (ndarray) – File Input / Output Methods

# np.save(): Saves an array in binary (.npy) format.
# np.load(): Loads an array from a .npy file.
# np.savetxt(): Saves an array to a text file.
# np.loadtxt(): Loads data from a text file.
# np.savez(): Saves multiple arrays in a single file.
# np.savez_compressed(): Saves multiple arrays in compressed format.

import numpy as np

# save()
a = np.array([1,2,3,4,5])

np.save("data.npy", a)

# load()
b = np.load("data.npy")
print(b)

# savetxt()
a = np.array([[1,2,3],
              [4,5,6]])

np.savetxt("data.txt", a)

# loadtxt()
b = np.loadtxt("data.txt")
print(b)

# savez()
a = np.array([1,2,3])
b = np.array([4,5,6])

np.savez("arrays.npz", arr1=a, arr2=b)

data = np.load("arrays.npz")
print(data["arr1"])
print(data["arr2"])

# savez_compressed()
np.savez_compressed("compressed.npz", arr1=a, arr2=b)

data = np.load("compressed.npz")
print(data["arr1"])
print(data["arr2"])

[1 2 3 4 5]
[[1. 2. 3.]
 [4. 5. 6.]]
[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


In [ ]:
# NumPy Array (ndarray) – Missing Value & Special Value Methods

# np.isnan(): Checks for NaN (Not a Number) values.
# np.isinf(): Checks for infinite values.
# np.isfinite(): Checks for finite values.
# np.nan_to_num(): Replaces NaN and Infinity with numeric values.

# np.nanmean(): Computes mean ignoring NaN values.
# np.nanmedian(): Computes median ignoring NaN values.
# np.nanstd(): Computes standard deviation ignoring NaN values.
# np.nanvar(): Computes variance ignoring NaN values.

# np.nanmin(): Returns minimum ignoring NaN values.
# np.nanmax(): Returns maximum ignoring NaN values.
# np.nansum(): Returns sum ignoring NaN values.

import numpy as np

a = np.array([1, np.nan, 3, np.inf, -np.inf])

# isnan()
print(np.isnan(a))

# isinf()
print(np.isinf(a))

# isfinite()
print(np.isfinite(a))

# nan_to_num()
print(np.nan_to_num(a))

b = np.array([1, 2, np.nan, 4, 5])

# nanmean()
print(np.nanmean(b))

# nanmedian()
print(np.nanmedian(b))

# nanstd()
print(np.nanstd(b))

# nanvar()
print(np.nanvar(b))

# nanmin()
print(np.nanmin(b))

# nanmax()
print(np.nanmax(b))

# nansum()
print(np.nansum(b))

[False  True False False False]
[False False False  True  True]
[ True False  True False False]
[ 1.00000000e+000  0.00000000e+000  3.00000000e+000  1.79769313e+308
 -1.79769313e+308]
3.0
3.0
1.5811388300841898
2.5
1.0
5.0
12.0


In [ ]:
# NumPy Array (ndarray) – Broadcasting & Vectorization Methods

# np.broadcast_to(): Broadcasts an array to a new shape.
# np.broadcast_arrays(): Broadcasts multiple arrays to a common shape.
# np.vectorize(): Converts a Python function to work element-wise on arrays.

# Concepts:
# Broadcasting: Automatically expands smaller arrays during operations.
# Vectorization: Performs operations on entire arrays without loops.

import numpy as np

# Broadcasting Example
a = np.array([1,2,3])

b = np.array([[10],
              [20],
              [30]])

print(a + b)

# broadcast_to()
a = np.array([1,2,3])

print(np.broadcast_to(a, (3,3)))

# broadcast_arrays()
a = np.array([1,2,3])

b = np.array([[10],
              [20],
              [30]])

x, y = np.broadcast_arrays(a, b)

print(x)
print(y)

# vectorize()
def square(x):
    return x ** 2

vectorized_square = np.vectorize(square)

a = np.array([1,2,3,4,5])

print(vectorized_square(a))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[10 10 10]
 [20 20 20]
 [30 30 30]]
[ 1  4  9 16 25]


In [ ]:
# NumPy Array (ndarray) – Iteration & Traversal Methods

# nditer(): Efficiently iterates over array elements.
# ndenumerate(): Iterates with index and value.
# ndindex(): Iterates over array indices.
# flat: Returns a 1D iterator over the array.
# flatiter: Iterator object returned by flat.

import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])

# nditer()
print("nditer():")
for x in np.nditer(a):
    print(x, end=" ")

print("\n")

# ndenumerate()
print("ndenumerate():")
for index, value in np.ndenumerate(a):
    print(index, value)

print()

# ndindex()
print("ndindex():")
for index in np.ndindex(a.shape):
    print(index, a[index])

print()

# flat
print("flat:")
for x in a.flat:
    print(x, end=" ")

print()

# flatiter
print(type(a.flat))

nditer():
1 2 3 4 5 6 

ndenumerate():
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6

ndindex():
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6

flat:
1 2 3 4 5 6 
<class 'numpy.flatiter'>


In [ ]:
# NumPy Array (ndarray) – Bitwise Operations

# np.bitwise_and(): Performs bitwise AND operation.
# np.bitwise_or(): Performs bitwise OR operation.
# np.bitwise_xor(): Performs bitwise XOR operation.
# np.bitwise_not(): Performs bitwise NOT operation.
# np.left_shift(): Shifts bits to the left.
# np.right_shift(): Shifts bits to the right.

import numpy as np

a = np.array([10, 12])
b = np.array([5, 6])

# bitwise_and()
print(np.bitwise_and(a, b))

# bitwise_or()
print(np.bitwise_or(a, b))

# bitwise_xor()
print(np.bitwise_xor(a, b))

# bitwise_not()
print(np.bitwise_not(a))

# left_shift()
print(np.left_shift(a, 1))

# right_shift()
print(np.right_shift(a, 1))

[0 4]
[15 14]
[15 10]
[-11 -13]
[20 24]
[5 6]


In [ ]:
# NumPy Array (ndarray) – Advanced Mathematical Functions

# np.exp(): Calculates exponential (e^x).
# np.log(): Calculates natural logarithm.
# np.log10(): Calculates base-10 logarithm.
# np.log2(): Calculates base-2 logarithm.
# np.sin(): Calculates sine values.
# np.cos(): Calculates cosine values.
# np.tan(): Calculates tangent values.
# np.deg2rad(): Converts degrees to radians.
# np.rad2deg(): Converts radians to degrees.
# np.hypot(): Calculates hypotenuse.
# np.square(): Squares each element.
# np.cbrt(): Calculates cube root.

import numpy as np

# exp()
a = np.array([1,2,3])
print(np.exp(a))

# log()
a = np.array([1,2,4,8])
print(np.log(a))

# log10()
print(np.log10(a))

# log2()
print(np.log2(a))

# sin()
a = np.array([0, np.pi/2, np.pi])
print(np.sin(a))

# cos()
print(np.cos(a))

# tan()
print(np.tan(a))

# deg2rad()
a = np.array([0,90,180])
print(np.deg2rad(a))

# rad2deg()
a = np.array([0,np.pi/2,np.pi])
print(np.rad2deg(a))

# hypot()
print(np.hypot(3,4))

# square()
a = np.array([1,2,3,4])
print(np.square(a))

# cbrt()
a = np.array([1,8,27,64])
print(np.cbrt(a))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.38629436 2.07944154]
[0.         0.30103    0.60205999 0.90308999]
[0. 1. 2. 3.]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[0.         1.57079633 3.14159265]
[  0.  90. 180.]
5.0
[ 1  4  9 16]
[1. 2. 3. 4.]
