<a href="https://colab.research.google.com/github/veluguladurgaprasad99/numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *NumPy*

 NumPy (Numerical Python) is a powerful Python library used for numerical computing. It provides a high-performance multidimensional array object and tools for working with arrays.

 NumPy is a Python library that allows efficient storage, manipulation, and mathematical operations on large amounts of numerical data.

```
# This is formatted as code
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)

Output

[10 20 30 40]
```
**Why NumPy?**

Python lists are useful, but they become slow when handling large amounts of data. NumPy solves this problem.

**Reasons to Use NumPy**
1.Faster Execution

NumPy arrays are stored in contiguous memory locations, making operations much faster.

2.Less Memory Usage

NumPy consumes less memory compared to Python lists.

3.Mathematical Operations

Supports vectorized operations without loops.

4.Multi-Dimensional Arrays

Can easily work with 1D, 2D, 3D, and higher-dimensional data.

5.Rich Function Library

Provides hundreds of mathematical and statistical functions.





In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr * 2)

[2 4 6 8]


**NumPy vs Python Lists**

Feature 	                  Python List	        NumPy Array

Speed	                      Slow	              Fast

Memory Usage	              More	              Less

Mathematical Operations	    Limited	            Powerful

Multi-Dimensional Support	  Poor	              Excellent

Data Type Consistency	      Mixed Types Allowed	Same Type Preferred

Scientific Computing	      Not Ideal	          Designed For It

In [ ]:
a = [1, 2, 3, 4]

result = []

for i in a:
    result.append(i * 2)

print(result)

[2, 4, 6, 8]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(a * 2)

[2 4 6 8]


**ndarray (NumPy Array)**

**ndarray stands for N-Dimensional Array.**

It is the core data structure of NumPy.

Definition

An ndarray is a collection of elements of the same data type stored in contiguous memory locations.

### **Creating an ndarray**

1. Creating Arrays

The most common way to create a NumPy array is using np.array().

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)

[10 20 30 40]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30])

print(type(arr))

<class 'numpy.ndarray'>


### 1D **Array**

In [ ]:
arr = np.array([1, 2, 3])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[1 2 3]
1
(3,)
3


# 2D **Array**

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


## **3D Array**

In [ ]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8


# 5. N-Dimensional Arrays

# NumPy supports any number of dimensions.

In [ ]:
import numpy as np

arr = np.array(
    [[[[1,2],[3,4]]]]
)

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[[[1 2]
   [3 4]]]]
4
(1, 1, 2, 2)
4


In [ ]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


# Advantages of **NumPy**
# 1. High Speed

Operations are implemented in optimized C code.

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr + 10)

[11 12 13 14]


# 2.Less Memory Consumption

NumPy arrays use less memory than Python lists.

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])

# 3. Vectorization

Apply operations to entire arrays without loops.

In [ ]:
import numpy as np

arr = np.array([1,2,3])

print(arr ** 2)

[1 4 9]


# 4. Multi-Dimensional Support

Works with matrices and tensors easily.

In [ ]:
import numpy as np

arr = np.array([[1,2],[3,4]])

print(arr)

[[1 2]
 [3 4]]


# 5. Powerful Mathematical Functions

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

10
2.5
4
